[rqlite]
uri = "http://id-generator-rqlite-0:4001"

[namespace]
allow-prefix = "test,plutus,benefit,notification,market,settlement"

[snowflake]
# max-id starts from 100 and max value is 1023
max-id = 100
