apiVersion: v1
kind: Service
metadata:
  name: id-generator-rqlite
spec:
  clusterIP: None
  publishNotReadyAddresses: True
  selector:
    app: id-generator-rqlite
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
